// Package policystore provides storage for Rego policy drafts and
// the active-policy pointer the gateway loads at startup and reloads
// on promote.
//
// # Mental model
//
// The gateway runs a single compiled Rego policy at any moment in
// time (see [policy.Engine]). Through v1.3 that source came from one
// of two places: the file pointed at by INTENTGATE_POLICY_FILE, or
// the embedded default. v1.4 adds a third source — a row in the
// "active policy pointer" stored here — and a workflow for editing
// candidates before promotion.
//
// Drafts are tenant-scoped (a per-tenant admin can save and list
// their own drafts; the superadmin can save and list everyone's).
// The active-policy pointer is intentionally GLOBAL: the gateway
// compiles one Rego module per process, and promoting a draft
// changes the policy every tenant sees. Promote and rollback
// therefore require the superadmin token; per-tenant admins can
// author drafts but not flip the live policy. Per-tenant active
// policies are a follow-on that requires either Rego composition or
// per-tenant module namespacing — out of scope for v1.4.
//
// # Rollback model
//
// Rollback is intentionally one-step. The active-policy row keeps
// the current and previous draft IDs; promote moves current→previous
// and writes the new current; rollback swaps them. Going back two
// versions means rolling back, then promoting an earlier draft
// again. This avoids dragging in a full version-history table and
// matches the pragmatic ops shape: "I just promoted something that
// broke prod; put back what was there a minute ago." Customers
// asking for full history get it via the audit log — every
// promote/rollback emits an audit event with both draft IDs.
//
// # Storage
//
//   - [MemoryStore] — in-process maps. Single-replica only, lost
//     on restart. Fine for dev and tests.
//   - [PostgresStore] — durable, multi-replica safe. The production
//     default once a Postgres URL is configured. Two tables with
//     idempotent embedded migration.
//
// # Concurrency
//
// All Store methods are safe for concurrent use. Promote is
// transactional (Postgres) or mutex-protected (memory) so a race
// between two operators promoting drafts can't produce an active
// row pointing at a deleted draft.
package policystore

import (
	"context"
	"encoding/json"
	"errors"
	"time"
)

// ErrNotFound is returned when a lookup misses.
var ErrNotFound = errors.New("policystore: not found")

// ErrActiveDraftDelete is returned when DeleteDraft is called on a
// draft that the active-policy pointer (current or previous) refers
// to. Operators must promote a different draft first or rollback to
// unpin the row before deletion is allowed — otherwise a single
// careless DELETE could orphan the active pointer.
var ErrActiveDraftDelete = errors.New("policystore: cannot delete a draft that is the current or previous active policy")

// Draft is a candidate Rego policy authored by an operator. It is
// not on the request path: the gateway never reads from a Draft
// directly. Promotion copies the Draft's source onto the active-
// policy pointer, which is what the gateway compiles.
type Draft struct {
	// ID is a short opaque identifier. Generated by the store on
	// create; clients never supply it.
	ID string `json:"id"`
	// Name is the operator-supplied label shown in the console list.
	// May be empty (the UI falls back to "Untitled draft").
	Name string `json:"name"`
	// Description is a longer free-form note. Optional.
	Description string `json:"description,omitempty"`
	// RegoSource is the full Rego module. The store does NOT compile
	// it — the admin handler does, before calling CreateDraft, so a
	// known-bad source never lands in the store.
	RegoSource string `json:"rego_source"`
	// Tenant scopes the draft. Per-tenant admins see only their
	// tenant's drafts; superadmin drafts carry empty tenant and are
	// visible only to the superadmin (matches the rest of the admin
	// API's tenancy semantics).
	Tenant string `json:"tenant,omitempty"`
	// CreatedAt is when the draft was first saved, in UTC. Updates
	// keep the original CreatedAt; UpdatedAt tracks the latest edit.
	CreatedAt time.Time `json:"created_at"`
	// UpdatedAt is the most recent save, in UTC.
	UpdatedAt time.Time `json:"updated_at"`
	// CreatedBy is the operator label (admin email / sub claim from
	// the console session, or "igctl" for CLI-authored drafts). May
	// be empty for older rows or when the caller doesn't supply it.
	CreatedBy string `json:"created_by,omitempty"`
}

// Active is one tenant's active-policy pointer. The store holds
// one row per tenant (empty Tenant = the default fallback row that
// applies to every tenant without their own promoted policy).
//
// The v1.4 design used a single 'global' row for the whole gateway;
// v1.5 evolves it into a per-tenant key while preserving the v1.4
// semantic for the empty-tenant slot. Operationally, that means:
//
//   - Single-tenant deployment: keep promoting against the default
//     slot (tenant=""), behavior is identical to v1.4.
//   - Multi-tenant deployment: per-tenant admins promote against
//     their own tenant slot; the gateway evaluates each request's
//     policy against the tenant's promoted module, falling back to
//     the default slot when the tenant hasn't promoted anything.
//
// CurrentDraftID points at the draft whose RegoSource the gateway
// has compiled for this tenant. Empty means "fall back to the
// default slot" (or, when this IS the default slot, "use the
// embedded default / file policy installed at startup").
type Active struct {
	// Tenant scopes the active pointer. Empty = default fallback.
	Tenant string `json:"tenant,omitempty"`
	// CurrentDraftID is what's compiled for this tenant right now.
	CurrentDraftID string `json:"current_draft_id,omitempty"`
	// PreviousDraftID is the rollback target. Empty when there is
	// nothing to roll back to.
	PreviousDraftID string `json:"previous_draft_id,omitempty"`
	// PromotedAt is when CurrentDraftID was promoted, in UTC. Zero
	// when no promote has happened yet. See MarshalJSON: time.Time's
	// zero value doesn't satisfy `omitempty` so we elide it manually
	// to avoid leaking "0001-01-01T00:00:00Z" into the API.
	PromotedAt time.Time `json:"promoted_at,omitempty"`
	// PromotedBy is the operator label captured at promote time.
	PromotedBy string `json:"promoted_by,omitempty"`
}

// MarshalJSON elides PromotedAt when it carries Go's zero time.
// Without this, a "no draft promoted yet" response would include
// `"promoted_at":"0001-01-01T00:00:00Z"`, which the console
// renders as "promoted on Jan 1, year 1" in the active-policy
// banner. Easiest to fix at the marshal step rather than scattering
// `if !.IsZero()` checks across every caller.
func (a Active) MarshalJSON() ([]byte, error) {
	type alias Active // avoid infinite recursion into our own MarshalJSON
	if a.PromotedAt.IsZero() {
		// Marshal a stripped copy with the time field cleared so
		// Go's default `omitempty` on the zero time string doesn't
		// trigger (the time itself is zero, but Format(RFC3339)
		// produces "0001-...", so we need the explicit alias path).
		return json.Marshal(struct {
			Tenant          string `json:"tenant,omitempty"`
			CurrentDraftID  string `json:"current_draft_id,omitempty"`
			PreviousDraftID string `json:"previous_draft_id,omitempty"`
			PromotedBy      string `json:"promoted_by,omitempty"`
		}{
			Tenant:          a.Tenant,
			CurrentDraftID:  a.CurrentDraftID,
			PreviousDraftID: a.PreviousDraftID,
			PromotedBy:      a.PromotedBy,
		})
	}
	return json.Marshal(alias(a))
}

// ListFilter narrows ListDrafts results. All fields are optional;
// the zero value returns every draft visible to the caller (with
// the store's own tenant scoping already applied by the handler).
type ListFilter struct {
	// Tenant scopes results. Empty means "all tenants" (superadmin
	// view); non-empty filters to that tenant's drafts.
	Tenant string
	// Limit caps page size. Zero falls back to the implementation's
	// default (typically 100). Clamped to 1000.
	Limit int
	// Offset enables pagination.
	Offset int
}

// Store is the contract every policystore backend implements.
//
// Implementations MUST be safe for concurrent use. Promote and
// Rollback MUST be atomic against concurrent callers: a partial
// update that leaves the active row pointing at a non-existent
// draft is a correctness bug.
type Store interface {
	// CreateDraft inserts a new draft. The store generates the ID
	// and sets CreatedAt/UpdatedAt to time.Now().UTC(). Returns the
	// fully populated draft (with the generated ID) so the caller
	// can return it to the operator.
	//
	// The store does NOT validate the Rego source — that's the
	// admin handler's job (compile-on-save catches typos at the
	// editor instead of at promote time).
	CreateDraft(ctx context.Context, d Draft) (Draft, error)

	// UpdateDraft replaces an existing draft's fields by ID. The
	// tenant on the input MUST match the stored row's tenant —
	// callers should pre-filter via Get to avoid leaking existence
	// across tenants. Returns ErrNotFound if the ID is unknown.
	UpdateDraft(ctx context.Context, d Draft) (Draft, error)

	// GetDraft returns one draft by ID. Returns ErrNotFound if the
	// ID is unknown. Callers are responsible for matching the
	// returned Tenant against the resolved admin tenant — the store
	// returns rows regardless of tenant so a single Get can serve
	// both superadmin and per-tenant callers.
	GetDraft(ctx context.Context, id string) (Draft, error)

	// ListDrafts returns drafts most-recent-first.
	ListDrafts(ctx context.Context, filter ListFilter) ([]Draft, error)

	// DeleteDraft removes a draft by ID. Returns ErrNotFound if the
	// ID is unknown, ErrActiveDraftDelete if the row is referenced
	// by ANY tenant's active-policy pointer (current OR previous).
	// The active-reference check sweeps every per-tenant row so a
	// draft pinned by another tenant's pointer is also protected.
	DeleteDraft(ctx context.Context, id string) error

	// GetActive returns the active-policy pointer for the given
	// tenant. Empty tenant returns the default-fallback row that
	// applies to every tenant without their own promoted policy
	// (the v1.4 "global" row in the new schema).
	//
	// Always returns a zero-value Active (with no error) when
	// nothing has been promoted yet for that tenant — the caller
	// distinguishes "no active set" via CurrentDraftID == "".
	GetActive(ctx context.Context, tenant string) (Active, error)

	// ListActive returns every tenant's active-policy pointer.
	// Used at startup so main.go can hydrate the reloader's full
	// map of engines in one pass instead of N round-trips per
	// configured tenant. Returns rows ordered by tenant (empty
	// first so the default fallback is processed before per-tenant
	// overlays, which is the order the reloader expects for clean
	// fallback dispatch when a tenant has no row yet).
	ListActive(ctx context.Context) ([]Active, error)

	// Promote sets the active-policy pointer for the given tenant
	// to draftID. The existing CurrentDraftID (if any) becomes
	// PreviousDraftID, so one rollback step is always available
	// immediately after a promote.
	//
	// promotedBy is the operator label for the active row.
	// Empty tenant operates on the default-fallback row.
	//
	// Returns ErrNotFound if draftID isn't a known draft. The
	// implementation MUST validate this inside the same transaction
	// (or under the same mutex) that updates the active row so a
	// promote can't race a delete and leave a dangling pointer.
	//
	// Idempotent in spirit: promoting the already-current draft is
	// a no-op (no audit event, no PromotedAt update). Implementations
	// detect this and return the unchanged Active without writing.
	Promote(ctx context.Context, draftID, promotedBy, tenant string) (Active, error)

	// Rollback swaps Current and Previous on the active-policy
	// pointer for the given tenant, then clears Previous (so two
	// consecutive rollbacks don't ping-pong). Returns ErrNotFound
	// when PreviousDraftID is empty — there is nothing to roll
	// back to. Empty tenant operates on the default-fallback row.
	//
	// rolledBackBy is captured into PromotedBy on the active row,
	// with the convention that the audit-log entry will distinguish
	// rollback from promote.
	Rollback(ctx context.Context, rolledBackBy, tenant string) (Active, error)

	// DeleteActive clears the tenant's active-policy pointer row
	// entirely. Requests from that tenant resume falling back to
	// the default-fallback slot (or, when this IS the default-
	// fallback slot, to the embedded / file policy installed at
	// startup). Useful when an operator has promoted a tenant-
	// specific policy and now wants to "revert to platform default"
	// without rolling back through their previous drafts one step
	// at a time.
	//
	// Empty tenant on the default-fallback row is a no-op (the row
	// is seeded by the migration and we don't want to leave the
	// gateway with no default-fallback row at all). Callers that
	// want to "reset" the default-fallback slot should promote a
	// fresh draft instead.
	//
	// Idempotent: clearing an already-empty / nonexistent row is
	// not an error — returns the zero-valued Active so the caller
	// can use the result as the post-state without checking error
	// kinds.
	//
	// Cross-replica: the Postgres implementation fires a NOTIFY
	// with a payload signaling the slot was cleared so sibling
	// replicas know to call Reloader.RemoveFor for that tenant.
	DeleteActive(ctx context.Context, tenant string) (Active, error)

	// Watch subscribes to active-pointer changes for the lifetime of
	// ctx. The returned channel delivers one [Active] value per
	// observed change; callers fetch the corresponding draft via
	// GetDraft, compile it, and Swap it onto their live policy
	// engine.
	//
	// Semantics:
	//
	//   - No initial value is delivered. Callers should always seed
	//     their state with [GetActive] before starting Watch — the
	//     watcher then keeps that state fresh.
	//   - The channel is buffered (small). A slow consumer that fails
	//     to drain it can miss notifications, in which case the
	//     polling fallback (PostgresStore) or the next Promote/
	//     Rollback (MemoryStore) eventually delivers a fresh value
	//     for the same field. The consumer's reaction is itself
	//     idempotent — comparing the incoming current_draft_id
	//     against the locally-loaded one short-circuits no-op
	//     refreshes — so a few extra channel sends never hurt.
	//   - The channel closes when ctx is cancelled (or when Close
	//     is called on the store).
	//
	// Implementations MUST tolerate any number of concurrent
	// watchers; production deployments expect one per gateway
	// replica. The PostgresStore uses LISTEN/NOTIFY for the wakeup,
	// with a 5-second polling fallback so reconnect windows can't
	// leave a replica running stale policy indefinitely.
	Watch(ctx context.Context) (<-chan Active, error)

	// Close releases resources (the Postgres connection pool, etc.).
	// Safe to call multiple times. Memory store's Close is a no-op
	// for the pool but does close any outstanding Watch channels so
	// callers blocked on the channel see a clean exit.
	Close() error
}
